"""Render a :class:`GraphSpec` as a runnable Python source file.

The output uses the same hand-written style as ``fleet new`` and the
bundled examples — ``FleetLLM(...)``, ``Agent(...)``, ``Graph(...)``
chains, and an ``if __name__ == "__main__":`` runner — so a user who
designs a graph visually can drop down to code without rewriting it.
"""
from __future__ import annotations

import keyword

from fleet.graphspec.spec import AgentSpec, GraphSpec, NodeSpec

def _header(name: str) -> str:
    safe_name = name.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return (
        f'"""Graph: {safe_name} — generated by fleet.graphspec.spec_to_python."""\n'
        "from __future__ import annotations\n"
        "\n"
        "import asyncio\n"
        "\n"
        "from fleet import Agent, Graph\n"
        "from fleet.core.state import GraphState\n"
        "from fleet.providers.client import FleetLLM\n"
    )

_FOOTER_TEMPLATE = (
    'if __name__ == "__main__":\n'
    '    state = GraphState(goal="Replace this with your goal.")\n'
    "    final = asyncio.run(graph.run(state))\n"
    "    if final.messages:\n"
    "        print(final.messages[-1].content)\n"
)


def spec_to_python(spec: GraphSpec) -> str:
    """Render a :class:`GraphSpec` as a runnable Python source file."""
    parts: list[str] = [
        _header(spec.name),
        "",
        _agents_block(spec),
        "",
        _graph_block(spec),
        "",
        _FOOTER_TEMPLATE,
    ]
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# agents section
# ---------------------------------------------------------------------------

def _agents_block(spec: GraphSpec) -> str:
    lines: list[str] = []
    for node in spec.nodes:
        lines.append(_agent_for_node(node))
    return "\n\n".join(lines)


def _agent_for_node(node: NodeSpec) -> str:
    ident = _safe_ident(node.id)
    agent: AgentSpec = node.agent
    llm_kwargs = [_kw("backend", agent.provider), _kw("model", agent.model)]
    if agent.base_url:
        llm_kwargs.append(_kw("base_url", agent.base_url))
    llm_args = ", ".join(llm_kwargs)

    tools_repr = "[" + ", ".join(_pyrepr(t) for t in agent.tools) + "]"
    agent_kwargs = [
        f"name={_pyrepr(agent.name)}",
        f"goal={_pyrepr(agent.system)}",
        f"tools={tools_repr}",
        f"max_iters={agent.max_iters}",
    ]
    if agent.memory_bank:
        agent_kwargs.append("memory_bank=__import__('fleet').memory.ReasoningBank()")

    return (
        f"_llm_{ident} = FleetLLM({llm_args})\n"
        f"{ident} = Agent(\n"
        f"    _llm_{ident},\n"
        + "".join(f"    {kw},\n" for kw in agent_kwargs)
        + ")"
    )


# ---------------------------------------------------------------------------
# graph section
# ---------------------------------------------------------------------------

def _graph_block(spec: GraphSpec) -> str:
    lines: list[str] = [
        "graph = (",
        f"    Graph({_pyrepr(spec.name)})",
    ]
    for node in spec.nodes:
        ident = _safe_ident(node.id)
        lines.append(f"    .add_node({_pyrepr(node.id)}, {ident}.step)")
    for edge in spec.edges:
        if edge.cond is None:
            lines.append(f"    .add_edge({_pyrepr(edge.src)}, {_pyrepr(edge.dst)})")
        else:
            lines.append(
                f"    .add_edge({_pyrepr(edge.src)}, {_pyrepr(edge.dst)}, "
                f"cond=__cond({_pyrepr(edge.cond)}))"
            )
    lines.append(f"    .set_entry({_pyrepr(spec.entry)})")
    lines.append(f"    .set_exit({_pyrepr(spec.exit)})")
    lines.append("    .compile()")
    lines.append(")")

    body = "\n".join(lines)

    if any(edge.cond for edge in spec.edges):
        helper = (
            "def __cond(name: str):\n"
            "    from fleet.graphspec.conditions import get_condition\n"
            "\n"
            "    fn = get_condition(name)\n"
            "    if fn is None:\n"
            '        raise ValueError(f"Unknown condition: {name!r}")\n'
            "    return fn\n"
            "\n"
            "\n"
        )
        return helper + body

    return body


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _safe_ident(node_id: str) -> str:
    """Turn a node id into a valid Python identifier."""
    out_chars: list[str] = []
    for ch in node_id:
        if ch.isalnum() or ch == "_":
            out_chars.append(ch)
        else:
            out_chars.append("_")
    out = "".join(out_chars) or "node"
    if out[0].isdigit():
        out = "_" + out
    if keyword.iskeyword(out):
        out = out + "_"
    return out


def _kw(name: str, value: object) -> str:
    return f"{name}={_pyrepr(value)}"


def _pyrepr(value: object) -> str:
    """Stable repr for str/int/bool/None — never embeds tracebacks."""
    return repr(value)
